<a href="https://colab.research.google.com/github/deorebhumika06/ai-projects/blob/main/2%20project%20of%20cleaning%20part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("/content/netflix1.csv.zip")
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [6]:
df.describe().round()

       release_year
count        8790.0
mean         2014.0
std             9.0
min          1925.0
25%          2013.0
50%          2017.0
75%          2019.0
max          2021.0

In [9]:
df.isnull().sum()/len(df)*100

show_id         0.0
type            0.0
title           0.0
director        0.0
country         0.0
date_added      0.0
release_year    0.0
rating          0.0
duration        0.0
listed_in       0.0
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dropna().shape

(8790, 10)

In [20]:
df.shape

(8790, 10)

In [21]:
df[df.duplicated()].shape

(0, 10)

In [24]:
for col in df.columns:
  if df[col].unique:
    print(col)
    print(df[col].value_counts())
    print("-"*50)

show_id
show_id
s8786    1
s1       1
s3       1
s6       1
s14      1
        ..
s941     1
s940     1
s13      1
s939     1
s10      1
Name: count, Length: 8790, dtype: int64
--------------------------------------------------
type
type
Movie      6126
TV Show    2664
Name: count, dtype: int64
--------------------------------------------------
title
title
9-Feb                                2
15-Aug                               2
22-Jul                               2
Septiembre, un llanto en silencio    1
Set Up                               1
                                    ..
Sei                                  1
Superlopez                           1
Oversize Cops                        1
Mirage                               1
The Highwaymen                       1
Name: count, Length: 8787, dtype: int64
--------------------------------------------------
director
director
Not Given                 2588
Rajiv Chilaka               20
Alastair Fothergill         18
Raúl Campos, Jan Suter      18
Marcus Raboy                16
                          ...
Mark Risley                  1
Kirati Nakintanon            1
Christian De Vita            1
Abu Bakr Shawky              1
N. Chandra                   1
Name: count, Length: 4528, dtype: int64
--------------------------------------------------
country
country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64
--------------------------------------------------
date_added
date_added
1/1/2020      110
11/1/2019      91
3/1/2018       75
12/31/2019     74
10/1/2018      71
             ...
12/2/2015       1
9/22/2016       1
9/17/2016       1
5/4/2017        1
9/20/2021       1
Name: count, Length: 1713, dtype: int64
--------------------------------------------------
release_year
release_year
2018    1146
2019    1030
2017    1030
2020     953
2016     901
        ...
1961       1
1959       1
1925       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64
--------------------------------------------------
rating
rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64
--------------------------------------------------
duration
duration
1 Season      1791
2 Seasons      421
3 Seasons      198
90 min         152
94 min         146
              ...
191 min          1
17 Seasons       1
10 min           1
312 min          1
11 Seasons       1
Name: count, Length: 220, dtype: int64
--------------------------------------------------
listed_in
listed_in
Dramas, International Movies                               362
Documentaries                                              359
Stand-Up Comedy                                            334
Comedies, Dramas, International Movies                     274
Dramas, Independent Movies, International Movies           252
                                                          ...
TV Action & Adventure, TV Comedies                           1
Romantic TV Shows, Spanish-Language TV Shows, TV Dramas      1
Classic & Cult TV, Kids' TV, Spanish-Language TV Shows       1
Anime Series, Crime TV Shows, TV Thrillers                   1
British TV Shows, Docuseries, Reality TV                     1
Name: count, Length: 513, dtype: int64
--------------------------------------------------

In [33]:
import re

In [36]:
def export_duration(duration):
  duration_count=re.findall('[0-9]+',str(duration))
  if len(duration_count) > 0:
    return int(duration_count[0])
  else:
    return None
df['duration']=df['duration'].apply(export_duration)

In [37]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90,0
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1,0
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1,0
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91,0
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125,0

In [43]:
df.dropna(subset=('type'),inplace=True)

In [42]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [46]:
df.dropna(subset=['show_id'],inplace=True)

In [47]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [49]:
df['director'].unique()

array(['Kirsten Johnson', 'Julien Leclercq', 'Mike Flanagan', ...,
       'Majid Al Ansari', 'Peter Hewitt', 'Mozez Singh'], dtype=object)

In [50]:
df['title'].unique()

array(['Dick Johnson Is Dead', 'Ganglands', 'Midnight Mass', ...,
       'Zindagi Gulzar Hai', 'Yoko', 'YOM'], dtype=object)

In [51]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.dtypes

show_id         object
type            object
title           object
director        object
country         object
date_added      object
release_year     int64
rating          object
duration         int64
listed_in        int64
dtype: object

In [56]:
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90,0
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1,0
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1,0
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91,0
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125,0
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2,0
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3,0
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1,0
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1,0
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1,0

In [59]:
import re

In [60]:
def export_show_id(show_id):
  show_count=re.findall('[0-9]+',str(show_id))
  if len(show_count) > 0:
    return int(show_count[0])
  else:
    return None
df['show_id']=df['show_id'].apply(export_show_id)

In [61]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90,0
1,3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1,0
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1,0
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91,0
4,8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125,0

In [62]:
df['show_id'].value_counts()

show_id
8786    1
1       1
3       1
6       1
14      1
       ..
941     1
940     1
13      1
939     1
10      1
Name: count, Length: 8790, dtype: int64

In [64]:
df.dtypes

show_id          int64
type            object
title           object
director        object
country         object
date_added      object
release_year     int64
rating          object
duration         int64
listed_in        int64
dtype: object

In [65]:
import re

In [70]:
def export_data(date_added):
  data_count=re.findall('[0-9]+',str(date_added))
  if len(data_count) > 0:
    return int(data_count[0])
  else:
    return None
df['show_id']=df['show_id'].apply(export_data)

In [71]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90,0
1,3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1,0
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1,0
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91,0
4,8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125,0

In [72]:
df.dtypes

show_id          int64
type            object
title           object
director        object
country         object
date_added      object
release_year     int64
rating          object
duration         int64
listed_in        int64
dtype: object

In [77]:
df['year'] = df['date_added'].dt.year

In [78]:
df['month'] = df['date_added'].dt.month

In [80]:
df['day'] = df['date_added'].dt.day

In [82]:
df['date_added'] = pd.to_datetime(df['date_added'])

In [83]:
df.dtypes

show_id                  int64
type                    object
title                   object
director                object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                 int64
listed_in                int64
year                     int32
month                    int32
day                      int32
dtype: object

In [84]:
df.describe()

,show_id,date_added,release_year,duration,listed_in,year,month,day
count,8790.000000,8790,8790.000000,8790.000000,8790.0,8790.000000,8790.000000,8790.000000
mean,4399.382366,2019-05-17 21:44:01.638225408,2014.183163,69.934471,0.0,2018.873606,6.655859,12.500000
min,1.000000,2008-01-01 00:00:00,1925.000000,1.000000,0.0,2008.000000,1.000000,1.000000
25%,2198.250000,2018-04-06 00:00:00,2013.000000,2.000000,0.0,2018.000000,4.000000,1.000000
50%,4395.500000,2019-07-03 00:00:00,2017.000000,88.500000,0.0,2019.000000,7.000000,13.000000
75%,6598.750000,2020-08-19 18:00:00,2019.000000,106.000000,0.0,2020.000000,10.000000,20.000000
max,8807.000000,2021-09-25 00:00:00,2021.000000,312.000000,0.0,2021.000000,12.000000,31.000000
std,2542.575288,NaN,8.825466,50.794433,0.0,1.573568,3.436103,9.887635

In [86]:
df.dropna(subset=('date_added'),inplace=True)

In [88]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
year            0
month           0
day             0
dtype: int64

In [89]:
df.describe()

,show_id,date_added,release_year,duration,listed_in,year,month,day
count,8790.000000,8790,8790.000000,8790.000000,8790.0,8790.000000,8790.000000,8790.000000
mean,4399.382366,2019-05-17 21:44:01.638225408,2014.183163,69.934471,0.0,2018.873606,6.655859,12.500000
min,1.000000,2008-01-01 00:00:00,1925.000000,1.000000,0.0,2008.000000,1.000000,1.000000
25%,2198.250000,2018-04-06 00:00:00,2013.000000,2.000000,0.0,2018.000000,4.000000,1.000000
50%,4395.500000,2019-07-03 00:00:00,2017.000000,88.500000,0.0,2019.000000,7.000000,13.000000
75%,6598.750000,2020-08-19 18:00:00,2019.000000,106.000000,0.0,2020.000000,10.000000,20.000000
max,8807.000000,2021-09-25 00:00:00,2021.000000,312.000000,0.0,2021.000000,12.000000,31.000000
std,2542.575288,NaN,8.825466,50.794433,0.0,1.573568,3.436103,9.887635

In [91]:
df.dropna(subset=['show_id'], inplace=True)

In [92]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
year            0
month           0
day             0
dtype: int64

In [93]:
df.shape

(8790, 13)

In [94]:
df.duplicated().sum()

np.int64(0)