<a href="https://colab.research.google.com/github/deorebhumika06/ai-projects/blob/main/3%20project%20of%20cleaning%20part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pf
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df=pf.read_csv("/content/Automobile.csv")
df.head()

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa

In [7]:
df.info(())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          398 non-null    object
 1   mpg           398 non-null    float64
 2   cylinders     398 non-null    int64
 3   displacement  398 non-null    float64
 4   horsepower    392 non-null    float64
 5   weight        398 non-null    int64
 6   acceleration  398 non-null    float64
 7   model_year    398 non-null    int64
 8   origin        398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [11]:
df.describe().sum()/len(df)*50

mpg               69.652080
cylinders         54.290927
displacement     217.769563
horsepower       138.876953
weight          2462.753316
acceleration      62.264545
model_year       107.752221
dtype: float64

In [14]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [15]:
df.shape

(398, 9)

In [18]:
df[df.duplicated()].shape

(0, 9)

In [19]:
df['name'].value_counts()

name
ford pinto             6
ford maverick          5
amc matador            5
toyota corolla         5
amc hornet             4
                      ..
amc concord dl         1
volkswagen rabbit l    1
mazda glc custom l     1
mazda glc custom       1
chevy s-10             1
Name: count, Length: 305, dtype: int64

In [20]:
df[df['name'] == 'ford pinto']

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
32,ford pinto,25.0,4,98.0,NaN,2046,19.0,71,usa
112,ford pinto,19.0,4,122.0,85.0,2310,18.5,73,usa
130,ford pinto,26.0,4,122.0,80.0,2451,16.5,74,usa
168,ford pinto,23.0,4,140.0,83.0,2639,17.0,75,usa
174,ford pinto,18.0,6,171.0,97.0,2984,14.5,75,usa
206,ford pinto,26.5,4,140.0,72.0,2565,13.6,76,usa

In [29]:
df.duplicated().sum()

np.int64(0)

In [34]:
df['cylinders'].value_counts()

cylinders
4    158
8     80
6     60
3      4
5      3
Name: count, dtype: int64

In [35]:
df[df['cylinders'] == '4']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [36]:
df.drop_duplicates('cylinders')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
14,toyota corona mark ii,24.0,4,113.0,95.0,2372,15.0,70,japan
15,plymouth duster,22.0,6,198.0,95.0,2833,15.5,70,usa
71,mazda rx2 coupe,19.0,3,70.0,97.0,2330,13.5,72,japan
274,audi 5000,20.3,5,131.0,103.0,2830,15.9,78,europe

In [37]:
df['displacement'].value_counts()

displacement
350.0    15
318.0    15
97.0     14
98.0     13
250.0    12
         ..
81.0      1
141.0     1
145.0     1
181.0     1
144.0     1
Name: count, Length: 78, dtype: int64

In [40]:
df[df['displacement'] == '350']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [42]:
df['displacement'].value_counts()

displacement
350.0    15
318.0    15
97.0     14
98.0     13
250.0    12
         ..
81.0      1
141.0     1
145.0     1
181.0     1
144.0     1
Name: count, Length: 78, dtype: int64

In [43]:
df.drop_duplicates('displacement')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
359,peugeot 505s turbo diesel,28.1,4,141.0,80.0,3230,20.4,81,europe
360,volvo diesel,30.7,6,145.0,76.0,3160,19.6,81,europe
367,chevrolet cavalier,28.0,4,112.0,88.0,2605,19.6,82,usa
386,buick century limited,25.0,6,181.0,110.0,2945,16.4,82,usa
390,toyota celica gt,32.0,4,144.0,96.0,2665,13.9,82,japan

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df['horsepower'].value_counts()

horsepower
150.0    17
88.0     15
90.0     14
110.0    14
100.0    10
         ..
132.0     1
64.0      1
116.0     1
79.0      1
82.0      1
Name: count, Length: 87, dtype: int64

In [46]:
df[df['horsepower'] == '150.0']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [47]:
df['origin'].value_counts()

origin
usa       187
japan      60
europe     58
Name: count, dtype: int64

In [48]:
df[df['origin'] == 'usa']

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
392,chevrolet camaro,27.0,4,151.0,90.0,2950,17.3,82,usa
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [49]:
df.drop_duplicates('origin')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
14,toyota corona mark ii,24.0,4,113.0,95.0,2372,15.0,70,japan
19,volkswagen 1131 deluxe sedan,26.0,4,97.0,46.0,1835,20.5,70,europe

In [51]:
df[df.duplicated()].sum()

name              0
mpg             0.0
cylinders         0
displacement    0.0
horsepower      0.0
weight            0
acceleration    0.0
model_year        0
origin            0
dtype: object

In [52]:
df['acceleration'].value_counts()

acceleration
14.5    18
15.5    16
14.0    14
15.0    11
19.0    11
        ..
17.1     1
13.9     1
15.6     1
24.6     1
11.6     1
Name: count, Length: 91, dtype: int64

In [53]:
df[df['acceleration'] == '14.5']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [54]:
df.dropna(subset=('acceleration'))

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [56]:
df.drop_duplicates('acceleration')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,70,usa
...,...,...,...,...,...,...,...,...,...
365,ford granada gl,20.2,6,200.0,88.0,3060,17.1,81,usa
390,toyota celica gt,32.0,4,144.0,96.0,2665,13.9,82,japan
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df[df.duplicated()].sum()

name              0
mpg             0.0
cylinders         0
displacement    0.0
horsepower      0.0
weight            0
acceleration    0.0
model_year        0
origin            0
dtype: object

In [59]:
df['model_year'].value_counts()

model_year
73    32
78    31
70    29
82    27
77    25
72    24
79    24
81    22
71    22
80    20
76    19
75    16
74    14
Name: count, dtype: int64

In [60]:
df[df['model_year'] == '81']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [61]:
df.drop_duplicates('model_year')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
30,chevrolet vega 2300,28.0,4,140.0,90.0,2264,15.5,71,usa
57,toyota corona hardtop,24.0,4,113.0,95.0,2278,15.5,72,japan
85,buick century 350,13.0,8,350.0,175.0,4100,13.0,73,usa
128,chevrolet nova,15.0,6,250.0,100.0,3336,17.0,74,usa
152,plymouth valiant custom,19.0,6,225.0,95.0,3264,16.0,75,usa
182,fiat 131,28.0,4,107.0,86.0,2464,15.5,76,europe
216,honda accord cvcc,31.5,4,98.0,68.0,2045,18.5,77,japan
244,volkswagen rabbit custom diesel,43.1,4,90.0,48.0,1985,21.5,78,europe
280,pontiac lemans v6,21.5,6,231.0,115.0,3245,15.4,79,usa
310,toyota corolla tercel,38.1,4,89.0,60.0,1968,18.8,80,japan
338,plymouth reliant,27.2,4,135.0,84.0,2490,15.7,81,usa
367,chevrolet cavalier,28.0,4,112.0,88.0,2605,19.6,82,usa

In [64]:
df.dropna(subset=('model_year'),inplace=True)

In [67]:
df['model_year'].isnull().sum()

np.int64(0)

In [71]:
for col in df.columns:
  if df[col].nunique():
    print(col)
    print(df[col].value_counts())
    print('-'*50)

name
name
chevy s-10                1
plymouth horizon miser    1
mazda glc custom          1
mazda glc custom l        1
volkswagen rabbit l       1
                         ..
ford galaxie 500          1
ford torino               1
amc rebel sst             1
plymouth satellite        1
buick skylark 320         1
Name: count, Length: 305, dtype: int64
--------------------------------------------------
mpg
mpg
13.0    19
15.0    13
18.0    12
26.0    11
14.0    10
        ..
28.1     1
24.2     1
26.6     1
34.0     1
44.0     1
Name: count, Length: 111, dtype: int64
--------------------------------------------------
cylinders
cylinders
4    158
8     80
6     60
3      4
5      3
Name: count, dtype: int64
--------------------------------------------------
displacement
displacement
350.0    15
318.0    15
97.0     14
98.0     13
250.0    12
         ..
81.0      1
141.0     1
145.0     1
181.0     1
144.0     1
Name: count, Length: 78, dtype: int64
--------------------------------------------------
horsepower
horsepower
150.0    17
88.0     15
90.0     14
110.0    14
100.0    10
         ..
132.0     1
64.0      1
116.0     1
79.0      1
82.0      1
Name: count, Length: 87, dtype: int64
--------------------------------------------------
weight
weight
1985    4
2125    3
2130    3
2720    3
2265    2
       ..
2124    1
2379    1
2279    1
4499    1
2158    1
Name: count, Length: 278, dtype: int64
--------------------------------------------------
acceleration
acceleration
14.5    18
15.5    16
14.0    14
15.0    11
19.0    11
        ..
17.1     1
13.9     1
15.6     1
24.6     1
11.6     1
Name: count, Length: 91, dtype: int64
--------------------------------------------------
model_year
model_year
73    32
78    31
70    29
82    27
77    25
72    24
79    24
81    22
71    22
80    20
76    19
75    16
74    14
Name: count, dtype: int64
--------------------------------------------------
origin
origin
usa       187
japan      60
europe     58
Name: count, dtype: int64
--------------------------------------------------

In [72]:
df.dropna(subset=('name'),inplace=True)

In [75]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      5
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [78]:
import re

In [79]:
def extract_horsepower(horsepower):
  horsepower_no=re.findall('[0-9]+',str(horsepower))
  if len(horsepower_no)>0:
    return int(horsepower_no[0])
  else:
    return None
df['horsepower']=df['horsepower'].apply(extract_horsepower)

In [80]:
df['horsepower'].head()

0    130.0
1    165.0
2    150.0
3    150.0
4    140.0
Name: horsepower, dtype: float64

In [81]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      5
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [82]:
df['horsepower'].value_counts()

horsepower
150.0    17
88.0     15
90.0     14
110.0    14
100.0    10
         ..
132.0     1
64.0      1
116.0     1
79.0      1
82.0      1
Name: count, Length: 87, dtype: int64

In [83]:
df[df['horsepower'] == '150.0']

Empty DataFrame
Columns: [name, mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin]
Index: []

In [84]:
df.drop_duplicates('horsepower')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,70,usa
...,...,...,...,...,...,...,...,...,...
350,plymouth horizon 4,34.7,4,105.0,63.0,2215,14.9,81,usa
353,volkswagen jetta,33.0,4,105.0,74.0,2190,14.2,81,europe
361,toyota cressida,25.4,6,168.0,116.0,2900,12.6,81,japan
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [86]:
df.drop_duplicates('horsepower')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,70,usa
...,...,...,...,...,...,...,...,...,...
350,plymouth horizon 4,34.7,4,105.0,63.0,2215,14.9,81,usa
353,volkswagen jetta,33.0,4,105.0,74.0,2190,14.2,81,europe
361,toyota cressida,25.4,6,168.0,116.0,2900,12.6,81,japan
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [89]:
df[df.duplicated()].sum()

name              0
mpg             0.0
cylinders         0
displacement    0.0
horsepower      0.0
weight            0
acceleration    0.0
model_year        0
origin            0
dtype: object

In [90]:
df = df.dropna(subset=['horsepower'])

In [91]:
df=df.dropna()

In [ ]:
df['horsepower'] = df['horsepower'].fillna(0)

In [92]:
df['horsepower'].isnull().sum()

np.int64(0)

In [93]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [95]:
df[df.duplicated()].sum()

name              0
mpg             0.0
cylinders         0
displacement    0.0
horsepower      0.0
weight            0
acceleration    0.0
model_year        0
origin            0
dtype: object