<a href="https://colab.research.google.com/github/deorebhumika06/ai-projects/blob/main/4%20project%20of%20cleaning%20part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pf
import matplotlib.pyplot as pla
import seaborn as sns

In [3]:
df=pf.read_csv("/content/indian_ecommerce_pricing_revenue_growth_36_months (1).csv")
df.head()

,order_id,order_date,state,zone,category,brand_type,customer_gender,customer_age,base_price,discount_percent,final_price,units_sold,revenue,sales_event,competition_intensity,inventory_pressure
0,ORD0000001,2023-01-31,West Bengal,East,Fashion,Mass,Male,28,1810.89,65.00,633.81,29,18380.49,Normal,Medium,High
1,ORD0000002,2023-01-31,Gujarat,West,Sports & Fitness,Mass,Male,19,5678.15,50.83,2791.95,67,187060.65,Normal,Medium,High
2,ORD0000003,2023-01-31,Delhi NCR,North,Grocery Essentials,Mass,Male,25,169.98,35.26,110.05,57,6272.85,Normal,Medium,Low
3,ORD0000004,2023-01-31,Madhya Pradesh,Central,Footwear,Mass,Female,30,3244.91,61.94,1235.01,55,67925.55,Normal,High,High
4,ORD0000005,2023-01-31,Haryana,North,Fashion,Premium,Female,33,697.44,48.27,360.79,29,10462.91,Festival,Medium,High

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               30600 non-null  object
 1   order_date             30600 non-null  object
 2   state                  30600 non-null  object
 3   zone                   30600 non-null  object
 4   category               30600 non-null  object
 5   brand_type             30600 non-null  object
 6   customer_gender        30600 non-null  object
 7   customer_age           30600 non-null  int64
 8   base_price             30600 non-null  float64
 9   discount_percent       30600 non-null  float64
 10  final_price            30600 non-null  float64
 11  units_sold             30600 non-null  int64
 12  revenue                30600 non-null  float64
 13  sales_event            30600 non-null  object
 14  competition_intensity  30600 non-null  object
 15  inventory_pressure     30600 non-null  object
dtypes: float64(4), int64(2), object(10)
memory usage: 3.7+ MB

In [7]:
df.describe().sum()/len(df)*100

customer_age         100.766147
base_price           204.579283
discount_percent     100.763725
final_price          182.295563
units_sold           100.983943
revenue             4062.402933
dtype: float64

In [8]:
df.isnull().sum()

order_id                 0
order_date               0
state                    0
zone                     0
category                 0
brand_type               0
customer_gender          0
customer_age             0
base_price               0
discount_percent         0
final_price              0
units_sold               0
revenue                  0
sales_event              0
competition_intensity    0
inventory_pressure       0
dtype: int64

In [10]:
df.shape

(30600, 16)

In [13]:
df[df.duplicated].shape

(0, 16)

In [17]:
import re

In [19]:
for col in df.columns:
  if df[col].nunique():
    print(col)
    print(df[col])
    print("_"*50)

order_id
0        ORD0000001
1        ORD0000002
2        ORD0000003
3        ORD0000004
4        ORD0000005
            ...
30595    ORD0030596
30596    ORD0030597
30597    ORD0030598
30598    ORD0030599
30599    ORD0030600
Name: order_id, Length: 30600, dtype: object
__________________________________________________
order_date
0        2023-01-31
1        2023-01-31
2        2023-01-31
3        2023-01-31
4        2023-01-31
            ...
30595    2025-12-31
30596    2025-12-31
30597    2025-12-31
30598    2025-12-31
30599    2025-12-31
Name: order_date, Length: 30600, dtype: object
__________________________________________________
state
0           West Bengal
1               Gujarat
2             Delhi NCR
3        Madhya Pradesh
4               Haryana
              ...
30595     Uttar Pradesh
30596           Haryana
30597            Odisha
30598       West Bengal
30599       Maharashtra
Name: state, Length: 30600, dtype: object
__________________________________________________
zone
0           East
1           West
2          North
3        Central
4          North
          ...
30595      North
30596      North
30597       East
30598       East
30599       West
Name: zone, Length: 30600, dtype: object
__________________________________________________
category
0                   Fashion
1          Sports & Fitness
2        Grocery Essentials
3                  Footwear
4                   Fashion
                ...
30595     Premium Lifestyle
30596              Footwear
30597              Footwear
30598      Sports & Fitness
30599              Footwear
Name: category, Length: 30600, dtype: object
__________________________________________________
brand_type
0           Mass
1           Mass
2           Mass
3           Mass
4        Premium
          ...
30595       Mass
30596    Premium
30597       Mass
30598       Mass
30599    Premium
Name: brand_type, Length: 30600, dtype: object
__________________________________________________
customer_gender
0          Male
1          Male
2          Male
3        Female
4        Female
          ...
30595      Male
30596      Male
30597    Female
30598    Female
30599      Male
Name: customer_gender, Length: 30600, dtype: object
__________________________________________________
customer_age
0        28
1        19
2        25
3        30
4        33
         ..
30595    54
30596    18
30597    58
30598    23
30599    21
Name: customer_age, Length: 30600, dtype: int64
__________________________________________________
base_price
0         1810.89
1         5678.15
2          169.98
3         3244.91
4          697.44
           ...
30595    12463.98
30596     3974.58
30597     3020.42
30598     1212.05
30599      824.75
Name: base_price, Length: 30600, dtype: float64
__________________________________________________
discount_percent
0        65.00
1        50.83
2        35.26
3        61.94
4        48.27
         ...
30595    38.99
30596    39.35
30597    65.00
30598    12.35
30599    24.21
Name: discount_percent, Length: 30600, dtype: float64
__________________________________________________
final_price
0         633.81
1        2791.95
2         110.05
3        1235.01
4         360.79
          ...
30595    7604.27
30596    2410.58
30597    1057.15
30598    1062.36
30599     625.08
Name: final_price, Length: 30600, dtype: float64
__________________________________________________
units_sold
0        29
1        67
2        57
3        55
4        29
         ..
30595    11
30596    20
30597    59
30598     8
30599    16
Name: units_sold, Length: 30600, dtype: int64
__________________________________________________
revenue
0         18380.49
1        187060.65
2          6272.85
3         67925.55
4         10462.91
           ...
30595     83646.97
30596     48211.60
30597     62371.85
30598      8498.88
30599     10001.28
Name: revenue, Length: 30600, dtype: float64
__________________________________________________
sales_event
0          Normal
1          Normal
2          Normal
3          Normal
4        Festival
           ...
30595      Normal
30596    Festival
30597    Festival
30598      Normal
30599      Normal
Name: sales_event, Length: 30600, dtype: object
__________________________________________________
competition_intensity
0        Medium
1        Medium
2        Medium
3          High
4        Medium
          ...
30595    Medium
30596       Low
30597      High
30598    Medium
30599    Medium
Name: competition_intensity, Length: 30600, dtype: object
__________________________________________________
inventory_pressure
0        High
1        High
2         Low
3        High
4        High
         ...
30595     Low
30596     Low
30597     Low
30598     Low
30599     Low
Name: inventory_pressure, Length: 30600, dtype: object
__________________________________________________

In [20]:
df.dropna(subset=('state'),inplace=True)

In [23]:
df.dropna()

,order_id,order_date,state,zone,category,brand_type,customer_gender,customer_age,base_price,discount_percent,final_price,units_sold,revenue,sales_event,competition_intensity,inventory_pressure
0,ORD0000001,2023-01-31,West Bengal,East,Fashion,Mass,Male,28,1810.89,65.00,633.81,29,18380.49,Normal,Medium,High
1,ORD0000002,2023-01-31,Gujarat,West,Sports & Fitness,Mass,Male,19,5678.15,50.83,2791.95,67,187060.65,Normal,Medium,High
2,ORD0000003,2023-01-31,Delhi NCR,North,Grocery Essentials,Mass,Male,25,169.98,35.26,110.05,57,6272.85,Normal,Medium,Low
3,ORD0000004,2023-01-31,Madhya Pradesh,Central,Footwear,Mass,Female,30,3244.91,61.94,1235.01,55,67925.55,Normal,High,High
4,ORD0000005,2023-01-31,Haryana,North,Fashion,Premium,Female,33,697.44,48.27,360.79,29,10462.91,Festival,Medium,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30595,ORD0030596,2025-12-31,Uttar Pradesh,North,Premium Lifestyle,Mass,Male,54,12463.98,38.99,7604.27,11,83646.97,Normal,Medium,Low
30596,ORD0030597,2025-12-31,Haryana,North,Footwear,Premium,Male,18,3974.58,39.35,2410.58,20,48211.60,Festival,Low,Low
30597,ORD0030598,2025-12-31,Odisha,East,Footwear,Mass,Female,58,3020.42,65.00,1057.15,59,62371.85,Festival,High,Low
30598,ORD0030599,2025-12-31,West Bengal,East,Sports & Fitness,Mass,Female,23,1212.05,12.35,1062.36,8,8498.88,Normal,Medium,Low
30599,ORD0030600,2025-12-31,Maharashtra,West,Footwear,Premium,Male,21,824.75,24.21,625.08,16,10001.28,Normal,Medium,Low

In [25]:
import re

In [30]:
def export_city(state):
  state_no=re.findall('[0-9]+',str(state))
  if len(state_no)>0:
    return int(state_no[0])
  else:
    return None
df['state']=df['state'].apply(export_city)

In [31]:
df.isnull().sum()

order_id                     0
order_date                   0
state                    30600
zone                         0
category                     0
brand_type                   0
customer_gender              0
customer_age                 0
base_price                   0
discount_percent             0
final_price                  0
units_sold                   0
revenue                      0
sales_event                  0
competition_intensity        0
inventory_pressure           0
dtype: int64

In [32]:
df['state'].value_counts()

Series([], Name: count, dtype: int64)

In [67]:
df=df.dropna(subset=('state'),inplace=True)

In [34]:
df.dropna()

Empty DataFrame
Columns: [order_id, order_date, state, zone, category, brand_type, customer_gender, customer_age, base_price, discount_percent, final_price, units_sold, revenue, sales_event, competition_intensity, inventory_pressure]
Index: []

In [35]:
df['state']=df['state'].fillna(0)

In [36]:
df.isnull().sum()

order_id                 0
order_date               0
state                    0
zone                     0
category                 0
brand_type               0
customer_gender          0
customer_age             0
base_price               0
discount_percent         0
final_price              0
units_sold               0
revenue                  0
sales_event              0
competition_intensity    0
inventory_pressure       0
dtype: int64

In [37]:
df['order_id']=df['order_id'].astype(int)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               0 non-null      int64
 1   order_date             0 non-null      object
 2   state                  0 non-null      object
 3   zone                   0 non-null      object
 4   category               0 non-null      object
 5   brand_type             0 non-null      object
 6   customer_gender        0 non-null      object
 7   customer_age           0 non-null      int64
 8   base_price             0 non-null      float64
 9   discount_percent       0 non-null      float64
 10  final_price            0 non-null      float64
 11  units_sold             0 non-null      int64
 12  revenue                0 non-null      float64
 13  sales_event            0 non-null      object
 14  competition_intensity  0 non-null      object
 15  inventory_pressure     0 non-null      object
dtypes: float64(4), int64(3), object(9)
memory usage: 0.0+ bytes

In [42]:
df['order_date']=pf.to_datetime(df['order_date'])

In [44]:
df['customer_gender']=df['customer_gender'].astype('category')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               0 non-null      int64
 1   order_date             0 non-null      datetime64[ns]
 2   state                  0 non-null      object
 3   zone                   0 non-null      object
 4   category               0 non-null      object
 5   brand_type             0 non-null      object
 6   customer_gender        0 non-null      category
 7   customer_age           0 non-null      int64
 8   base_price             0 non-null      float64
 9   discount_percent       0 non-null      float64
 10  final_price            0 non-null      float64
 11  units_sold             0 non-null      int64
 12  revenue                0 non-null      float64
 13  sales_event            0 non-null      object
 14  competition_intensity  0 non-null      object
 15  inventory_pressure     0 non-null      object
dtypes: category(1), datetime64[ns](1), float64(4), int64(3), object(7)
memory usage: 108.0+ bytes

AttributeError: 'NoneType' object has no attribute 'sum'

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               0 non-null      int64
 1   order_date             0 non-null      datetime64[ns]
 2   state                  0 non-null      object
 3   zone                   0 non-null      object
 4   category               0 non-null      object
 5   brand_type             0 non-null      object
 6   customer_gender        0 non-null      category
 7   customer_age           0 non-null      int64
 8   base_price             0 non-null      float64
 9   discount_percent       0 non-null      float64
 10  final_price            0 non-null      float64
 11  units_sold             0 non-null      int64
 12  revenue                0 non-null      float64
 13  sales_event            0 non-null      object
 14  competition_intensity  0 non-null      object
 15  inventory_pressure     0 non-null      object
dtypes: category(1), datetime64[ns](1), float64(4), int64(3), object(7)
memory usage: 108.0+ bytes

In [64]:
df.isnull().sum()

order_id                 0
order_date               0
state                    0
zone                     0
category                 0
brand_type               0
customer_gender          0
customer_age             0
base_price               0
discount_percent         0
final_price              0
units_sold               0
revenue                  0
sales_event              0
competition_intensity    0
inventory_pressure       0
dtype: int64

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df.dtypes

order_id                          int64
order_date               datetime64[ns]
state                            object
zone                             object
category                         object
brand_type                       object
customer_gender                category
customer_age                      int64
base_price                      float64
discount_percent                float64
final_price                     float64
units_sold                        int64
revenue                         float64
sales_event                      object
competition_intensity            object
inventory_pressure               object
dtype: object

In [53]:
df['brand_type'].unique()

array([], dtype=object)

In [54]:
df['brand_type'].isnull().sum()

np.int64(0)

In [55]:
df.dropna()

Empty DataFrame
Columns: [order_id, order_date, state, zone, category, brand_type, customer_gender, customer_age, base_price, discount_percent, final_price, units_sold, revenue, sales_event, competition_intensity, inventory_pressure]
Index: []

In [56]:
df.columns

Index(['order_id', 'order_date', 'state', 'zone', 'category', 'brand_type',
       'customer_gender', 'customer_age', 'base_price', 'discount_percent',
       'final_price', 'units_sold', 'revenue', 'sales_event',
       'competition_intensity', 'inventory_pressure'],
      dtype='object')

In [57]:
df.shape

(0, 16)

In [58]:
df.shape
df['brand_type'].head()
df['brand_type'].isnull().sum()
df.columns

Index(['order_id', 'order_date', 'state', 'zone', 'category', 'brand_type',
       'customer_gender', 'customer_age', 'base_price', 'discount_percent',
       'final_price', 'units_sold', 'revenue', 'sales_event',
       'competition_intensity', 'inventory_pressure'],
      dtype='object')

In [59]:
df['brand_type'].unique()

array([], dtype=object)

In [65]:
df.describe().sum()

order_id            0.0
order_date            0
customer_age        0.0
base_price          0.0
discount_percent    0.0
final_price         0.0
units_sold          0.0
revenue             0.0
dtype: object

In [63]:
df.shape

(0, 16)

In [ ]:
import pandas as pf

In [68]:
df=pf.read_csv('/content/indian_ecommerce_pricing_revenue_growth_36_months (1).csv')
df.shape

(30600, 16)

In [71]:
df.fillna(method='ffill',inplace=True)

/tmp/ipykernel_9319/4116506308.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',inplace=True)

In [72]:
df.isnull().sum()

order_id                 0
order_date               0
state                    0
zone                     0
category                 0
brand_type               0
customer_gender          0
customer_age             0
base_price               0
discount_percent         0
final_price              0
units_sold               0
revenue                  0
sales_event              0
competition_intensity    0
inventory_pressure       0
dtype: int64

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.dtypes

order_id                  object
order_date                object
state                     object
zone                      object
category                  object
brand_type                object
customer_gender           object
customer_age               int64
base_price               float64
discount_percent         float64
final_price              float64
units_sold                 int64
revenue                  float64
sales_event               object
competition_intensity     object
inventory_pressure        object
dtype: object

In [76]:
df['order_id'] = df['order_id'].str.replace('ORD', '').astype(int)

In [77]:
df['order_date']=pf.to_datetime(df['order_date'])

In [78]:
df.dtypes

order_id                          int64
order_date               datetime64[ns]
state                            object
zone                             object
category                         object
brand_type                       object
customer_gender                  object
customer_age                      int64
base_price                      float64
discount_percent                float64
final_price                     float64
units_sold                        int64
revenue                         float64
sales_event                      object
competition_intensity            object
inventory_pressure               object
dtype: object

In [79]:
df['customer_age'].unique()

array([28, 19, 25, 30, 33, 47, 23, 45, 40, 22, 21, 34, 29, 53, 44, 31, 27,
       46, 49, 18, 36, 20, 41, 37, 48, 52, 26, 51, 63, 24, 43, 32, 35, 39,
       42, 61, 64, 38, 59, 57, 50, 55, 54, 62, 58, 65, 60, 56])