<a href="https://colab.research.google.com/github/deorebhumika06/ai-projects/blob/main/data%20cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
df=pd.read_csv("/content/Instagram visits clustering.csv")
df

      User ID  Instagram visit score  Spending_rank(0 to 100)
0           0                     63                24.050708
1           1                     61                25.223290
2           2                    104                18.528245
3           3                     82                86.890232
4           4                     14                31.492397
...       ...                    ...                      ...
2595     2595                     25                25.745908
2596     2596                     52                 9.275066
2597     2597                    100                84.999487
2598     2598                     87                20.530806
2599     2599                     34                76.388622

[2600 rows x 3 columns]

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User ID                  2600 non-null   int64
 1   Instagram visit score    2600 non-null   int64
 2   Spending_rank(0 to 100)  2600 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 61.1 KB

In [72]:
df.describe().round()

       User ID  Instagram visit score  Spending_rank(0 to 100)
count   2600.0                 2600.0                   2600.0
mean    1300.0                   63.0                     43.0
std      751.0                   27.0                     29.0
min        0.0                    5.0                      1.0
25%      650.0                   38.0                     19.0
50%     1300.0                   72.0                     28.0
75%     1949.0                   86.0                     72.0
max     2599.0                  118.0                    107.0

In [73]:
df.isnull()

      User ID  Instagram visit score  Spending_rank(0 to 100)
0       False                  False                    False
1       False                  False                    False
2       False                  False                    False
3       False                  False                    False
4       False                  False                    False
...       ...                    ...                      ...
2595    False                  False                    False
2596    False                  False                    False
2597    False                  False                    False
2598    False                  False                    False
2599    False                  False                    False

[2600 rows x 3 columns]

In [76]:
df.isnull().sum()/len(df)*100

User ID                    0.0
Instagram visit score      0.0
Spending_rank(0 to 100)    0.0
dtype: float64

In [84]:
df[df.duplicated()]

Empty DataFrame
Columns: [User ID, Instagram visit score, Spending_rank(0 to 100)]
Index: []

In [80]:
df.dropna().shape

(2600, 3)

In [81]:
df.shape

(2600, 3)

In [82]:
df['Instagram visit score'].value_counts()

Instagram visit score
86     68
90     67
87     66
84     64
83     61
       ..
118     1
114     1
109     1
111     1
110     1
Name: count, Length: 106, dtype: int64

In [83]:
df[df['Instagram visit score'] == '86']

Empty DataFrame
Columns: [User ID, Instagram visit score, Spending_rank(0 to 100)]
Index: []

In [85]:
df.isnull().values.any()

np.False_

In [95]:
for col in df.columns:
  if df[col].nunique():
    print(col)
    print(df[col].value_counts())
    print('-'*50)

User ID
User ID
2599    1
0       1
1       1
2       1
3       1
       ..
12      1
11      1
10      1
9       1
8       1
Name: count, Length: 2600, dtype: int64
--------------------------------------------------
Instagram visit score
Instagram visit score
86     68
90     67
87     66
84     64
83     61
       ..
118     1
114     1
109     1
111     1
110     1
Name: count, Length: 106, dtype: int64
--------------------------------------------------
Spending_rank(0 to 100)
Spending_rank(0 to 100)
76.388622    1
24.050708    1
25.223290    1
18.528245    1
86.890232    1
            ..
23.936884    1
30.975041    1
24.465674    1
25.966622    1
80.829564    1
Name: count, Length: 2600, dtype: int64
--------------------------------------------------

In [96]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [97]:
df=pd.read_csv("/content/my_file (1).csv")
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [99]:
df.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [100]:
df.describe().round()

       Rank  Shows
count  20.0   20.0
mean   10.0  110.0
std     6.0   67.0
min     1.0   41.0
25%     6.0   59.0
50%    10.0   87.0
75%    15.0  134.0
max    20.0  325.0

In [101]:
df.isnull()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,False,False,False
7,False,True,True,False,False,False,False,False,False,False,False
8,False,True,True,False,False,False,False,False,False,False,False
9,False,True,True,False,False,False,False,False,False,False,False
10,False,True,True,False,False,False,False,False,False,False,False
11,False,True,False,False,False,False,False,False,False,False,False
12,False,True,True,False,False,False,False,False,False,False,False
13,False,False,True,False,False,False,False,False,False,False,False
14,False,False,True,False,False,False,False,False,False,False,False
15,False,True,True,False,False,False,False,False,False,False,False
16,False,True,True,False,False,False,False,False,False,False,False
17,False,True,True,False,False,False,False,False,False,False,False
18,False,True,True,False,False,False,False,False,False,False,False
19,False,True,True,False,False,False,False,False,False,False,False

In [102]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [103]:
df.isnull().sum()/len(df)*100

Rank                                 0.0
Peak                                55.0
All Time Peak                       70.0
Actual gross                         0.0
Adjusted gross (in 2022 dollars)     0.0
Artist                               0.0
Tour title                           0.0
Year(s)                              0.0
Shows                                0.0
Average gross                        0.0
Ref.                                 0.0
dtype: float64

In [104]:
df.dropna().shape

(5, 11)

In [105]:
df[df.duplicated()]

Empty DataFrame
Columns: [Rank, Peak, All Time Peak, Actual gross, Adjusted gross (in 2022 dollars), Artist, Tour title, Year(s), Shows, Average gross, Ref.]
Index: []

In [106]:
df['Peak'].value_counts()

Peak
1        2
2[4]     2
1[4]     1
2[7]     1
2[10]    1
1[20]    1
2[c]     1
Name: count, dtype: int64

In [108]:
df[df['Peak'] == '1']

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]

In [109]:
for col in df.columns:
  if df[col].nunique():
    print(col)
    print(df[col].value_counts())
    print('-'*50)

Rank
Rank
7     2
2     1
1     1
3     1
4     1
5     1
6     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
Name: count, dtype: int64
--------------------------------------------------
Peak
Peak
1        2
2[4]     2
1[4]     1
2[7]     1
2[10]    1
1[20]    1
2[c]     1
Name: count, dtype: int64
--------------------------------------------------
All Time Peak
All Time Peak
2         1
7[2]      1
2[5]      1
10[7]     1
10[9]     1
14[17]    1
Name: count, dtype: int64
--------------------------------------------------
Actual gross
Actual gross
$780,000,000       1
$579,800,000       1
$411,000,000       1
$397,300,000       1
$345,675,146       1
$305,158,363       1
$280,000,000       1
$257,600,000       1
$256,084,556       1
$250,400,000       1
$229,100,000[b]    1
$227,400,000       1
$204,000,000       1
$200,000,000       1
$194,000,000       1
$184,000,000       1
$170,000,000       1
$169,800,000       1
$167,700,000[e]    1
$150,000,000       1
Name: count, dtype: int64
--------------------------------------------------
Adjusted gross (in 2022 dollars)
Adjusted gross (in 2022 dollars)
$780,000,000    1
$579,800,000    1
$560,622,615    1
$454,751,555    1
$402,844,849    1
$388,978,496    1
$381,932,682    1
$257,600,000    1
$312,258,401    1
$309,141,878    1
$283,202,896    1
$295,301,479    1
$251,856,802    1
$299,676,265    1
$281,617,035    1
$227,452,347    1
$213,568,571    1
$207,046,755    1
$204,486,106    1
$185,423,109    1
Name: count, dtype: int64
--------------------------------------------------
Artist
Artist
Taylor Swift    4
Madonna         4
Beyoncé         3
Pink            3
Lady Gaga       2
Celine Dion     1
Katy Perry      1
Cher            1
Adele           1
Name: count, dtype: int64
--------------------------------------------------
Tour title
Tour title
The Eras Tour †                             1
Renaissance World Tour                      1
Sticky & Sweet Tour ‡[4][a]                 1
Beautiful Trauma World Tour                 1
Reputation Stadium Tour                     1
The MDNA Tour                               1
Taking Chances World Tour                   1
Summer Carnival †                           1
The Formation World Tour                    1
The 1989 World Tour                         1
The Mrs. Carter Show World Tour             1
The Monster Ball Tour *                     1
Prismatic World Tour                        1
Living Proof: The Farewell Tour ‡[21][a]    1
Confessions Tour                            1
The Truth About Love Tour                   1
Born This Way Ball                          1
Rebel Heart Tour                            1
Adele Live 2016                             1
The Red Tour                                1
Name: count, dtype: int64
--------------------------------------------------
Year(s)
Year(s)
2013–2014    3
2023–2024    2
2008–2009    2
2023         1
2018         1
2012         1
2016         1
2018–2019    1
2015         1
2009–2011    1
2014–2015    1
2002–2005    1
2006         1
2012–2013    1
2015–2016    1
2016–2017    1
Name: count, dtype: int64
--------------------------------------------------
Shows
Shows
56     2
85     2
156    1
53     1
88     1
131    1
41     1
49     1
132    1
203    1
151    1
325    1
60     1
142    1
98     1
82     1
121    1
86     1
Name: count, dtype: int64
--------------------------------------------------
Average gross
Average gross
$13,928,571    1
$10,353,571    1
$4,835,294     1
$2,546,795     1
$6,522,173     1
$3,467,709     1
$2,137,405     1
$6,282,927     1
$5,226,215     1
$2,945,882     1
$1,735,606     1
$1,118,227     1
$1,350,993     1
$615,385       1
$3,233,333     1
$1,295,775     1
$1,734,694     1
$2,070,732     1
$1,385,950     1
$1,744,186     1
Name: count, dtype: int64
--------------------------------------------------
Ref.
Ref.
[1]         1
[3]         1
[6]         1
[7]         1
[8]         1
[9]         1
[11]        1
[12]        1
[13]        1
[14]        1
[15][16]    1
[18]        1
[19]        1
[20]        1
[5]         1
[22]        1
[d]         1
[4]         1
[25]        1
[26]        1
Name: count, dtype: int64
--------------------------------------------------

In [117]:
df.dropna(subset=('All Time Peak'),inplace=True)

In [116]:
df.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [118]:
df.dropna(subset=('Peak'),inplace=True)

In [119]:
df.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [120]:
df['Rank'].unique()

array([1, 2, 3, 4, 6])

In [123]:
df['Shows'].unique()

array([ 56,  85, 156,  88])

In [132]:
import re

def extract_Show(Show):
    Show_num = re.findall('[0-9]+', str(Show))  # + use kar
    if len(Show_num) > 0:
        return int(Show_num[0])
    else:
        return None

df['Shows'] = df['Shows'].apply(extract_Show)

In [133]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,5,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,5,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,8,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,1,"$2,546,795",[7]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,8,"$3,467,709",[9]

In [138]:
import re
def extract_Ref(ref):
  ref_no=re.findall('[0-9]+',str(ref))
  if len(ref_no)>0:
    return int(ref_no[0])
  else:
    return None
df['Ref.']=df['Ref.'].apply(extract_Ref)

In [139]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,5,"$13,928,571",1
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,5,"$10,353,571",3
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,8,"$4,835,294",6
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,1,"$2,546,795",7
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,8,"$3,467,709",9

In [141]:
df['Ref.'].unique()

array([1, 3, 6, 7, 9])

In [143]:
import re
def extract_Year(year):
  year_num=re.findall('[0-9]+',str(year))
  if len(year_num) >0:
    return int(year_num[0])
  else:
    return None
df['Year(s)']=df['Year(s)'].apply(extract_Year)

In [147]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023,5,"$13,928,571",1
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,5,"$10,353,571",3
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008,8,"$4,835,294",6
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018,1,"$2,546,795",7
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,8,"$3,467,709",9

In [145]:
df['Year(s)'].unique()

array([2023, 2008, 2018, 2012])

In [158]:
year = df['Year(s)'].median()
df['Year(s)'] = df['Year(s)'].fillna(year)

In [161]:
df['Tour title'].unique()

array(['The Eras Tour †', 'Renaissance World Tour',
       'Sticky & Sweet Tour ‡[4][a]', 'Beautiful Trauma World Tour',
       'The MDNA Tour'], dtype=object)

In [162]:
df['Tour title'].isnull().sum()

np.int64(0)

In [165]:
name = df['Tour title'].mode()[0]
df['Tour title'] = df['Tour title'].fillna(name)

In [167]:
df['Tour title'].value_counts()

Tour title
The Eras Tour †                1
Renaissance World Tour         1
Sticky & Sweet Tour ‡[4][a]    1
Beautiful Trauma World Tour    1
The MDNA Tour                  1
Name: count, dtype: int64

In [169]:
import re

def clean_tour(name):
    name = re.sub(r'\[.*?\]', '', str(name))
    name = re.sub(r'[†‡]', '', name)
    return name.strip()

df['Tour title'] = df['Tour title'].apply(clean_tour)

In [170]:
df['Tour title'].unique()

array(['The Eras Tour', 'Renaissance World Tour', 'Sticky & Sweet Tour',
       'Beautiful Trauma World Tour', 'The MDNA Tour'], dtype=object)